AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Type: String
  CloudFrontDistributionArn:
    Type: String
    Default: ''
    Description: ARN of the CloudFront distribution (optional, provided on update)
  CloudFrontOriginAccessIdentity:
    Type: String
    Default: ''
    Description: CloudFront Origin Access Identity (optional, provided on update)

Conditions:
  HasCloudFrontDistribution: !Not [!Equals [!Ref CloudFrontDistributionArn, '']]
  HasCloudFrontOAI: !Not [!Equals [!Ref CloudFrontOriginAccessIdentity, '']]

Resources:
  # S3 Bucket for Website Content
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # S3 Bucket Policy for CloudFront (added only when CloudFront ARN is provided)
  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: HasCloudFrontOAI
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - 's3:GetObject'
        Effect: Allow
        Resource: !Sub "${AppBucket.Arn}/*"

Outputs:
  BucketName:
    Description: Name of S3 bucket to hold website content
    Value: !Ref AppBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  BucketRegionalDomainName:
    Description: Regional domain name of S3 bucket
    Value: !GetAtt AppBucket.RegionalDomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketRegionalDomainName"