name: Build, Push, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      STACK_NAME: 'bikepacker-tracker-backend'
      AWS_REGION: 'eu-west-2'
      ECR_REPOSITORY: 992382417038.dkr.ecr.$AWS_REGION.amazonaws.com/bikepacker-tracker-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          cd backend
          docker build -t ${{ env.STACK_NAME }} .
          docker tag ${{ env.STACK_NAME }} ${{ env.ECR_REPOSITORY }}:latest

      - name: Create ECR repository if it doesn't exist
        run: |
          if ! aws ecr describe-repositories --repository-names ${{ env.STACK_NAME }} 2>/dev/null; then
            echo "Creating ECR repository ${{ env.STACK_NAME }}"
            aws ecr create-repository --repository-name ${{ env.STACK_NAME }}
          fi

      - name: Push Docker image to ECR and deploy
        run: |
          cd backend
          # Push the image and capture the digest
          DIGEST=$(docker push $ECR_REPO:latest | grep digest | cut -d' ' -f3)
          echo "Deploying stack ${{ env.STACK_NAME }} to region $AWS_REGION"
          aws cloudformation deploy \
            --capabilities CAPABILITY_IAM \
            --stack-name ${{ env.STACK_NAME }} \
            --template-file template.yaml \
            --region $AWS_REGION \
            --parameter-overrides \
              ImageUri="${DIGEST}"

      - name: Get API Gateway URL
        run: |
          echo "API Gateway URL:"
          aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs[?ExportName=='${{ env.STACK_NAME }}-ApiEndpoint'].OutputValue" --output text